### ISSUE TITLE
Review if automatic labeling is still valid 

### ISSUE THREAD

**Issue by criadoperez** [stacksgov/grants-dashboard#204]
Currently the following labels are assigned automatically, if the following keywords are found in the subject or body of an issue.
Are they still valid or they need to be updated?

          "keywords": ["Direct Application"], "labels": ["Direct Application"]}, 
          {"keywords": ["Wishlist Submission"], "labels": ["Wishlist Submission"]}, 
          {"keywords": ["Wishlist Request"], "labels": ["Wishlist Request"]}, 
          {"keywords": ["Open Source Dev 1st time Grantees"], "labels": ["Open Source First Time"]}, 
          {"keywords": ["Open Source Dev Repeat Grantees"], "labels": ["Open Source Repeat"]}, 
          {"keywords": ["Community Builder"], "labels": ["Community Builder"]}, 
          {"keywords": ["Education"], "labels": ["Education"]}, 
          {"keywords": ["Events"], "labels": ["Events"]}, 
          {"keywords": ["Chapter"], "labels": ["Chapter"]},
          {"keywords": ["ALEX Lab Foundation Grant"], "labels": ["ALEX Lab Foundation Grant"]},
          {"keywords": ["Stacks Protocol"], "labels": ["Stacks Protocol"]},
          {"keywords": ["Stacks Interface"], "labels": ["Stacks Interface"]},
          {"keywords": ["Stacks dApps & Clarity"], "labels": ["Stacks dApps & Clarity"]},
          {"keywords": ["Stacks Education & Community"], "labels": ["Stacks Education & Community"]}, 
          {"keywords": ["Stacks Developer Experience"], "labels": ["Stacks Developer Experience"]}, 
          {"keywords": ["Cross-Chain & Off-Chain"], "labels": ["Cross-Chain & Off-Chain"]}, 
          {"keywords": ["Bitcoin Utility"], "labels": ["Bitcoin Utility"]}]'

**Comment by criadoperez** [comment]
> ADD:  "label" ["Grant Type: Wishlist Idea"]

What keyword will trigger this new label?

The rest is all clear, thanks for the input.

**Comment by will-at-stacks** [comment]
clicking this option on the first page

<img width="1968" alt="image" src="https://user-images.githubusercontent.com/94402722/189726053-59a8a3f4-1788-43bf-8783-b5cc2569e0b0.png">

**Comment by criadoperez** [comment]
Ok, I'll check the code if there is label generated when that option is selected. On the github action there currently isn't any keyword for this label.

**Comment by criadoperez** [comment]
Merged fix https://github.com/stacksgov/Stacks-Grant-Launchpad/pull/683
