### ISSUE TITLE
Silent fail on Github action issues-change-columns

### ISSUE THREAD

**Issue by criadoperez** [stacksgov/grants-dashboard#206]
Github action "Issue Column Change Label" is silently failing as names of columns and labels have changed and are no longer valid.

### Current behavior
1. When issue is moved in the Project to column `Onboarding phase`:
     1. Add labels `Onboarding Phase`, `Onboarding in Progress`
     1. Remove labels `Application Phase`, `Initial Review in Progress`, `Review in Progress`, `Revisions in Progress`
1. When issue is moved in the Project to column `Milestone phase`:
     1. Add labels `Milestone in Progress, Milestone 1`
     1. Remove labels `Onboarding Phase`, `Application Phase`, `Initial Review in Progress`, `Review in Progress`, `Revisions in Progress`, `Onboarding in Progress`

@will-at-stacks , could you please confirm the new desired values below:

### New desired behavior 
1. When issue is moved in the Project to column `xxx` Grantee Onboarding?
     1. Add labels:
     1. Remove labels:
1. When issue is moved in the Project to column `yyy`
     1. Add labels:
     1. Remove labels:

**Comment by criadoperez** [comment]
Would this be the correct behavior now for the first part?

1. When issue is moved in the Project to column `Grantee Onboarding`
        1. Add labels: `Grant Status: (c) Grantee Onboarding`
        1. Remove labels: `Grant Status: (a) Application On Deck` and `Grant Status: (b) Application in Review`

**Comment by criadoperez** [comment]
First part fixed with https://github.com/stacksgov/Stacks-Grant-Launchpad/pull/683
Second part removed until we add the new desired behavior.

**Comment by will-at-stacks** [comment]
@criadoperez remember all of the 'Phase' labels were removed from the system.  
Also, when hardcoding label names please reference https://github.com/stacksgov/Stacks-Grant-Launchpad/labels . I created the labels already and the names are exactly what I want.  The only labels that are in this page that do not need to be considered are these:
![image](https://user-images.githubusercontent.com/94402722/189908094-8c48f385-bc19-4e12-83e9-18a5a495d02c.png)

The label names should ALWAYS start with the label type as a prefix:  
![image](https://user-images.githubusercontent.com/94402722/189909592-2a7b8be0-b37b-407d-b896-a349684e41ab.png)


Some feedback:

1. Add labels `Grant Status: (c) Grantee Onboarding` _(label name corrected and `Onboarding Phase` no longer applies)_

1. Add labels `Grant Status: (e) Completing Milestone 1` _(label name corrected)_

**Comment by will-at-stacks** [comment]
> @will-at-stacks , could you please confirm the new desired values below:
> 
> ### New desired behavior
> 1. When issue is moved in the Project to column `Grantee Onboarding`

1. Add labels: `Grant Status: (c) Grantee Onboarding`
2. Remove labels: `Grant Status: (b) Application in Review`

2. When issue is moved in the Project to column `Completing Initial Deliverable`
  
1. Add labels: `Grant Status: (d) Completing Initial Deliverable`
2. Remove labels: `Grant Status: (c) Grantee Onboarding`

**Comment by criadoperez** [comment]
Thanks @will-at-stacks for the input.

Yes, for the labels I always double check they exist in the github repo first and get the correct labeling from there.

Making the final changes and closing this issue soon.

As a note, in the remove labels, I'm keeping the extra remove labels. Meaning that if you move a grant to "Grantee Onboarding" it will remove the label (b) and (a) if it has either of them. Similar way, if you move a grant to "Completing Initial Deliverable", if will remove label (a), (b) and (c) if they exist. This is just to make sure, a Grant wont have more that one "Grant Status" label at the same time.
