### ISSUE TITLE
Integrate Github API to create Issues

### ISSUE THREAD

**Issue by vidiabtc** [stacksgov/grants-dashboard#56]
- New application will be auto-tagged and added to the Grant Applications Kanban board.

**Comment by wileyj** [comment]
question @will-at-stacks :
should this be created as an issue using the applicants github login
-or-
use a common account controlled by the foundation to create the issue via the API

**Comment by diopitis** [comment]
> 

I really like the flow of the user creating an issue from their login but the problem I see is that they would be able to edit their application once it has been approved changing milestone. 

This is solved with a common account posting on their behalf and assigning them to the issue but the experience just doesn't feel as good.
